name-template: "v$NEXT_PATCH_VERSION 🚀"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "Features ✨"
    labels:
      - feature
  - title: "Bug Fixes 🐛"
    labels:
      - bug
  - title: "Documentation 📝"
    labels:
      - docs
  - title: "Refactoring ⚡️"
    labels:
      - refactor
  - title: "Chores ⚙️"
    labels:
      - chore

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## Changes
  $CHANGES
