name: Label PRs from Conventional Commits
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Label PR based on commit
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          labels: |
            feat:feature
            fix:bug
            docs:docs
            chore:chore
            refactor:refactor
