name: Release Workflow

on:
  push:
    tags:
      - "*.*.*"

jobs:
  # -----------------------------------
  # Job 3: Build the package
  # -----------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.x

      - name: Install build dependencies
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  # -----------------------------------
  # Job 4: Publish to PyPI
  # -----------------------------------
  publish-pypi:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  # -----------------------------------
  # Job 5: Publish GitHub Release
  # -----------------------------------
  github-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: dist/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
